version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dexra_backend
    ports:
      - "9008:9008"
    env_file:
      - .env.prod
    restart: unless-stopped
